general {
  disable_loading_bar = true
  hide_cursor = true
  no_fade_in = false
}

background {
  monitor =
  color = rgba(17, 17, 27, 1.0) # crust
}

animations {
  enabled = true
}

input-field {
  monitor =
  size = 300, 60
  outline_thickness = 4
  dots_size = 0.2
  dots_spacing = 0.2
  dots_center = true
  outer_color = rgba(180, 190, 254, 1.0) # lavender
  inner_color = rgba(30, 30, 46, 0.8) # base
  font_color = rgba(205, 214, 244, 1.0) # text
  fade_on_empty = false
  placeholder_text = <span foreground="##cdd6f4"><i>Enter Password...</i></span>
  hide_input = false
  position = 0, -20
  halign = center
  valign = center
  rounding = 10
  check_color = rgba(166, 227, 161, 1.0) # green
  fail_color = rgba(243, 139, 168, 1.0) # red
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
}

label {
  monitor =
  text = $TIME
  color = rgba(205, 214, 244, 1.0)
  font_size = 64
  font_family = Cartograph CF Bold
  position = 0, 80
  halign = center
  valign = center
}
